<?php
/**
 * Export to PHP Array plugin for PHPMyAdmin
 * @version 0.2b
 */

//
// Database `db536226943`
//

// `db536226943`.`language_names`
$language_names = array(
  array('id' => '1','name' => '(Afan) Oromo','approved' => '1'),
  array('id' => '2','name' => 'Abkhazian','approved' => '1'),
  array('id' => '3','name' => 'Afar','approved' => '1'),
  array('id' => '4','name' => 'Afrikaans','approved' => '1'),
  array('id' => '5','name' => 'Albanian','approved' => '1'),
  array('id' => '6','name' => 'Amharic','approved' => '1'),
  array('id' => '7','name' => 'Arabic','approved' => '1'),
  array('id' => '8','name' => 'Armenian','approved' => '1'),
  array('id' => '9','name' => 'Assamese','approved' => '1'),
  array('id' => '10','name' => 'Austrian','approved' => '1'),
  array('id' => '11','name' => 'Aymara','approved' => '1'),
  array('id' => '12','name' => 'Azerbaijani','approved' => '1'),
  array('id' => '13','name' => 'Bashkir','approved' => '1'),
  array('id' => '14','name' => 'Basque','approved' => '1'),
  array('id' => '15','name' => 'Bengali','approved' => '1'),
  array('id' => '16','name' => 'Bhutani','approved' => '1'),
  array('id' => '17','name' => 'Bihari','approved' => '1'),
  array('id' => '18','name' => 'Bislama','approved' => '1'),
  array('id' => '19','name' => 'Breton','approved' => '1'),
  array('id' => '20','name' => 'Bulgarian','approved' => '1'),
  array('id' => '21','name' => 'Burmese','approved' => '1'),
  array('id' => '22','name' => 'Byelorussian','approved' => '1'),
  array('id' => '23','name' => 'Cambodian','approved' => '1'),
  array('id' => '24','name' => 'Cantonese','approved' => '1'),
  array('id' => '25','name' => 'Catalan','approved' => '1'),
  array('id' => '26','name' => 'Chinese','approved' => '1'),
  array('id' => '27','name' => 'Corsican','approved' => '1'),
  array('id' => '28','name' => 'Croatian','approved' => '1'),
  array('id' => '29','name' => 'Czech','approved' => '1'),
  array('id' => '30','name' => 'Danish','approved' => '1'),
  array('id' => '31','name' => 'Dutch','approved' => '1'),
  array('id' => '32','name' => 'English','approved' => '1'),
  array('id' => '33','name' => 'Esperanto','approved' => '1'),
  array('id' => '34','name' => 'Estonian','approved' => '1'),
  array('id' => '35','name' => 'Faeroese','approved' => '1'),
  array('id' => '36','name' => 'Fiji','approved' => '1'),
  array('id' => '37','name' => 'Finnish','approved' => '1'),
  array('id' => '38','name' => 'French','approved' => '1'),
  array('id' => '39','name' => 'Frisian','approved' => '1'),
  array('id' => '40','name' => 'Galician','approved' => '1'),
  array('id' => '41','name' => 'Georgian','approved' => '1'),
  array('id' => '42','name' => 'German','approved' => '1'),
  array('id' => '43','name' => 'Greek','approved' => '1'),
  array('id' => '44','name' => 'Greenlandic','approved' => '1'),
  array('id' => '45','name' => 'Guarani','approved' => '1'),
  array('id' => '46','name' => 'Gujarati','approved' => '1'),
  array('id' => '47','name' => 'Hausa','approved' => '1'),
  array('id' => '48','name' => 'Hebrew','approved' => '1'),
  array('id' => '49','name' => 'Hindi','approved' => '1'),
  array('id' => '50','name' => 'Hungarian','approved' => '1'),
  array('id' => '51','name' => 'Icelandic','approved' => '1'),
  array('id' => '52','name' => 'Indonesian','approved' => '1'),
  array('id' => '53','name' => 'Interlingua','approved' => '1'),
  array('id' => '54','name' => 'Interlingue','approved' => '1'),
  array('id' => '55','name' => 'Inupiak','approved' => '1'),
  array('id' => '56','name' => 'Irish','approved' => '1'),
  array('id' => '57','name' => 'Italian','approved' => '1'),
  array('id' => '58','name' => 'Japanese','approved' => '1'),
  array('id' => '59','name' => 'Javanese','approved' => '1'),
  array('id' => '60','name' => 'Kannada','approved' => '1'),
  array('id' => '61','name' => 'Kashmiri','approved' => '1'),
  array('id' => '62','name' => 'Kazakh','approved' => '1'),
  array('id' => '63','name' => 'Kinyarwanda','approved' => '1'),
  array('id' => '64','name' => 'Kirghiz','approved' => '1'),
  array('id' => '65','name' => 'Kirundi','approved' => '1'),
  array('id' => '66','name' => 'Korean','approved' => '1'),
  array('id' => '67','name' => 'Kurdish','approved' => '1'),
  array('id' => '68','name' => 'Laothian','approved' => '1'),
  array('id' => '69','name' => 'Latin','approved' => '1'),
  array('id' => '70','name' => 'Latvian, Lettish','approved' => '1'),
  array('id' => '71','name' => 'Lingala','approved' => '1'),
  array('id' => '72','name' => 'Lithuanian','approved' => '1'),
  array('id' => '73','name' => 'Luxembourgeois','approved' => '1'),
  array('id' => '74','name' => 'Macedonian','approved' => '1'),
  array('id' => '75','name' => 'Malagasy','approved' => '1'),
  array('id' => '76','name' => 'Malay','approved' => '1'),
  array('id' => '77','name' => 'Malayalam','approved' => '1'),
  array('id' => '78','name' => 'Maltese','approved' => '1'),
  array('id' => '79','name' => 'Mandarin','approved' => '1'),
  array('id' => '80','name' => 'Maori','approved' => '1'),
  array('id' => '81','name' => 'Marathi','approved' => '1'),
  array('id' => '82','name' => 'Moldavian','approved' => '1'),
  array('id' => '83','name' => 'Mongolian','approved' => '1'),
  array('id' => '84','name' => 'Nauru','approved' => '1'),
  array('id' => '85','name' => 'Nepali','approved' => '1'),
  array('id' => '86','name' => 'Norwegian','approved' => '1'),
  array('id' => '87','name' => 'Occitan','approved' => '1'),
  array('id' => '88','name' => 'Oriya','approved' => '1'),
  array('id' => '89','name' => 'Pashto, Pushto','approved' => '1'),
  array('id' => '90','name' => 'Persian','approved' => '1'),
  array('id' => '91','name' => 'Polish','approved' => '1'),
  array('id' => '92','name' => 'Portuguese','approved' => '1'),
  array('id' => '93','name' => 'Punjabi','approved' => '1'),
  array('id' => '94','name' => 'Quechua','approved' => '1'),
  array('id' => '95','name' => 'Rhaeto-Romance','approved' => '1'),
  array('id' => '96','name' => 'Romanian','approved' => '1'),
  array('id' => '97','name' => 'Russian','approved' => '1'),
  array('id' => '98','name' => 'Samoan','approved' => '1'),
  array('id' => '99','name' => 'Sangro','approved' => '1'),
  array('id' => '100','name' => 'Sanskrit','approved' => '1'),
  array('id' => '101','name' => 'Scots Gaelic','approved' => '1'),
  array('id' => '102','name' => 'Serbian','approved' => '1'),
  array('id' => '103','name' => 'Serbo-Croatian','approved' => '1'),
  array('id' => '104','name' => 'Sesotho','approved' => '1'),
  array('id' => '105','name' => 'Setswana','approved' => '1'),
  array('id' => '106','name' => 'Shona','approved' => '1'),
  array('id' => '107','name' => 'Sindhi','approved' => '1'),
  array('id' => '108','name' => 'Singhalese','approved' => '1'),
  array('id' => '109','name' => 'Siswati','approved' => '1'),
  array('id' => '110','name' => 'Slovak','approved' => '1'),
  array('id' => '111','name' => 'Slovenian','approved' => '1'),
  array('id' => '112','name' => 'Somali','approved' => '1'),
  array('id' => '113','name' => 'Spanish','approved' => '1'),
  array('id' => '114','name' => 'Sundanese','approved' => '1'),
  array('id' => '115','name' => 'Swahili','approved' => '1'),
  array('id' => '116','name' => 'Swedish','approved' => '1'),
  array('id' => '117','name' => 'Tagalog','approved' => '1'),
  array('id' => '118','name' => 'Tajik','approved' => '1'),
  array('id' => '119','name' => 'Tamil','approved' => '1'),
  array('id' => '120','name' => 'Tatar','approved' => '1'),
  array('id' => '121','name' => 'Telugu','approved' => '1'),
  array('id' => '122','name' => 'Thai','approved' => '1'),
  array('id' => '123','name' => 'Tibetan','approved' => '1'),
  array('id' => '124','name' => 'Tigrinya','approved' => '1'),
  array('id' => '125','name' => 'Tonga','approved' => '1'),
  array('id' => '126','name' => 'Tsonga','approved' => '1'),
  array('id' => '127','name' => 'Turkish','approved' => '1'),
  array('id' => '128','name' => 'Turkmen','approved' => '1'),
  array('id' => '129','name' => 'Twi','approved' => '1'),
  array('id' => '130','name' => 'Ukrainian','approved' => '1'),
  array('id' => '131','name' => 'Urdu','approved' => '1'),
  array('id' => '132','name' => 'Uzbek','approved' => '1'),
  array('id' => '133','name' => 'Vietnamese','approved' => '1'),
  array('id' => '134','name' => 'Volapuk','approved' => '1'),
  array('id' => '135','name' => 'Welsh','approved' => '1'),
  array('id' => '136','name' => 'Wolof','approved' => '1'),
  array('id' => '137','name' => 'Xhosa','approved' => '1'),
  array('id' => '138','name' => 'Yiddish','approved' => '1'),
  array('id' => '139','name' => 'Yoruba','approved' => '1'),
  array('id' => '140','name' => 'Zulu','approved' => '1'),
  array('id' => '141','name' => 'Vrtatchanski','approved' => '0'),
  array('id' => '142','name' => 'Other lang','approved' => '0'),
  array('id' => '143','name' => 'Strange Language','approved' => '0'),
  array('id' => '144','name' => 'TSHIVENDA','approved' => '0')
);
