<?php
/**
 * Export to PHP Array plugin for PHPMyAdmin
 * @version 0.2b
 */

//
// Database `db536226943`
//

// `db536226943`.`options`
$options = array(
  array('id' => '1','group_id' => '1','subcategory_id' => '2','category_id' => '1','name' => 'Advertising','_order' => '0'),
  array('id' => '2','group_id' => '1','subcategory_id' => '2','category_id' => '1','name' => 'Design','_order' => '0'),
  array('id' => '3','group_id' => '1','subcategory_id' => '2','category_id' => '1','name' => 'Marketing','_order' => '0'),
  array('id' => '4','group_id' => '1','subcategory_id' => '2','category_id' => '1','name' => 'Publishing','_order' => '0'),
  array('id' => '5','group_id' => '1','subcategory_id' => '2','category_id' => '1','name' => 'Art and Music','_order' => '0'),
  array('id' => '6','group_id' => '1','subcategory_id' => '2','category_id' => '1','name' => 'Journalism','_order' => '0'),
  array('id' => '7','group_id' => '1','subcategory_id' => '2','category_id' => '1','name' => 'PR','_order' => '0'),
  array('id' => '8','group_id' => '1','subcategory_id' => '2','category_id' => '1','name' => 'Theatre and Events','_order' => '0'),
  array('id' => '14','group_id' => '2','subcategory_id' => '2','category_id' => '1','name' => 'Accountancy','_order' => '0'),
  array('id' => '15','group_id' => '2','subcategory_id' => '2','category_id' => '1','name' => 'Asset Management','_order' => '0'),
  array('id' => '16','group_id' => '2','subcategory_id' => '2','category_id' => '1','name' => 'Consulting','_order' => '0'),
  array('id' => '17','group_id' => '2','subcategory_id' => '2','category_id' => '1','name' => 'Finance','_order' => '0'),
  array('id' => '18','group_id' => '2','subcategory_id' => '2','category_id' => '1','name' => 'Insurance','_order' => '0'),
  array('id' => '19','group_id' => '2','subcategory_id' => '2','category_id' => '1','name' => 'Investment Banking','_order' => '0'),
  array('id' => '20','group_id' => '2','subcategory_id' => '2','category_id' => '1','name' => 'Law','_order' => '0'),
  array('id' => '21','group_id' => '2','subcategory_id' => '2','category_id' => '1','name' => 'Tax','_order' => '0'),
  array('id' => '22','group_id' => '5','subcategory_id' => '5','category_id' => '2','name' => 'Art and Design','_order' => '0'),
  array('id' => '23','group_id' => '5','subcategory_id' => '5','category_id' => '2','name' => 'Art History','_order' => '0'),
  array('id' => '24','group_id' => '5','subcategory_id' => '5','category_id' => '2','name' => 'Classics','_order' => '0'),
  array('id' => '25','group_id' => '5','subcategory_id' => '5','category_id' => '2','name' => 'English Literature','_order' => '0'),
  array('id' => '26','group_id' => '5','subcategory_id' => '5','category_id' => '2','name' => 'English Language','_order' => '0'),
  array('id' => '27','group_id' => '5','subcategory_id' => '5','category_id' => '2','name' => 'Music','_order' => '0'),
  array('id' => '28','group_id' => '5','subcategory_id' => '5','category_id' => '2','name' => 'Philosophy','_order' => '0'),
  array('id' => '29','group_id' => '5','subcategory_id' => '5','category_id' => '2','name' => 'Religious Studies','_order' => '0'),
  array('id' => '30','group_id' => '5','subcategory_id' => '5','category_id' => '2','name' => 'Art History','_order' => '0'),
  array('id' => '31','group_id' => '6','subcategory_id' => '5','category_id' => '2','name' => 'Biology','_order' => '0'),
  array('id' => '32','group_id' => '6','subcategory_id' => '5','category_id' => '2','name' => 'Chemistry','_order' => '0'),
  array('id' => '33','group_id' => '6','subcategory_id' => '5','category_id' => '2','name' => 'Computing','_order' => '0'),
  array('id' => '34','group_id' => '6','subcategory_id' => '5','category_id' => '2','name' => 'Futher Maths','_order' => '0'),
  array('id' => '35','group_id' => '6','subcategory_id' => '5','category_id' => '2','name' => 'Maths','_order' => '0'),
  array('id' => '36','group_id' => '6','subcategory_id' => '5','category_id' => '2','name' => 'Physics','_order' => '0'),
  array('id' => '37','group_id' => '7','subcategory_id' => '5','category_id' => '2','name' => 'Economics','_order' => '0'),
  array('id' => '38','group_id' => '7','subcategory_id' => '5','category_id' => '2','name' => 'History','_order' => '0'),
  array('id' => '39','group_id' => '7','subcategory_id' => '5','category_id' => '2','name' => 'Geography','_order' => '0'),
  array('id' => '40','group_id' => '7','subcategory_id' => '5','category_id' => '2','name' => 'Politics','_order' => '0'),
  array('id' => '41','group_id' => '7','subcategory_id' => '5','category_id' => '2','name' => 'Psycology','_order' => '0'),
  array('id' => '42','group_id' => '7','subcategory_id' => '5','category_id' => '2','name' => 'Sociology','_order' => '0'),
  array('id' => '43','group_id' => '8','subcategory_id' => '5','category_id' => '2','name' => 'Business Studies','_order' => '0'),
  array('id' => '44','group_id' => '8','subcategory_id' => '5','category_id' => '2','name' => 'Design','_order' => '0'),
  array('id' => '45','group_id' => '8','subcategory_id' => '5','category_id' => '2','name' => 'Drama','_order' => '0'),
  array('id' => '46','group_id' => '8','subcategory_id' => '5','category_id' => '2','name' => 'Film Studies','_order' => '0'),
  array('id' => '47','group_id' => '8','subcategory_id' => '5','category_id' => '2','name' => 'Law','_order' => '0'),
  array('id' => '48','group_id' => '8','subcategory_id' => '5','category_id' => '2','name' => 'Media','_order' => '0'),
  array('id' => '49','group_id' => '3','subcategory_id' => '2','category_id' => '1','name' => 'Agriculture','_order' => '0'),
  array('id' => '50','group_id' => '3','subcategory_id' => '2','category_id' => '1','name' => 'Consumer Goods','_order' => '0'),
  array('id' => '51','group_id' => '3','subcategory_id' => '2','category_id' => '1','name' => 'Energy and Utilities','_order' => '0'),
  array('id' => '52','group_id' => '3','subcategory_id' => '2','category_id' => '1','name' => 'Health and Pharma','_order' => '0'),
  array('id' => '53','group_id' => '3','subcategory_id' => '2','category_id' => '1','name' => 'Industrials and Mining','_order' => '0'),
  array('id' => '54','group_id' => '3','subcategory_id' => '2','category_id' => '1','name' => 'Infrastructure','_order' => '0'),
  array('id' => '55','group_id' => '3','subcategory_id' => '2','category_id' => '1','name' => 'Retail and Hospitality','_order' => '0'),
  array('id' => '56','group_id' => '3','subcategory_id' => '2','category_id' => '1','name' => 'Technology and Media','_order' => '0'),
  array('id' => '57','group_id' => '4','subcategory_id' => '2','category_id' => '1','name' => 'Charity','_order' => '0'),
  array('id' => '58','group_id' => '4','subcategory_id' => '2','category_id' => '1','name' => 'Education','_order' => '0'),
  array('id' => '59','group_id' => '4','subcategory_id' => '2','category_id' => '1','name' => 'Human Resources','_order' => '0'),
  array('id' => '60','group_id' => '4','subcategory_id' => '2','category_id' => '1','name' => 'Local Government','_order' => '0'),
  array('id' => '61','group_id' => '4','subcategory_id' => '2','category_id' => '1','name' => 'Central Government','_order' => '0'),
  array('id' => '62','group_id' => '4','subcategory_id' => '2','category_id' => '1','name' => 'Politics','_order' => '0'),
  array('id' => '63','group_id' => '4','subcategory_id' => '2','category_id' => '1','name' => 'Sports','_order' => '0'),
  array('id' => '64','group_id' => '4','subcategory_id' => '2','category_id' => '1','name' => 'Start Ups','_order' => '0'),
  array('id' => '65','group_id' => '12','subcategory_id' => '2','category_id' => '2','name' => 'Working at Pace','_order' => '0'),
  array('id' => '66','group_id' => '12','subcategory_id' => '2','category_id' => '2','name' => 'Paying Attention to Detail','_order' => '0'),
  array('id' => '67','group_id' => '12','subcategory_id' => '2','category_id' => '2','name' => 'Taking on Responsibilities','_order' => '0'),
  array('id' => '68','group_id' => '12','subcategory_id' => '2','category_id' => '2','name' => 'Inspiring Confidence','_order' => '0'),
  array('id' => '69','group_id' => '12','subcategory_id' => '2','category_id' => '2','name' => 'Being a Team Player','_order' => '0'),
  array('id' => '70','group_id' => '12','subcategory_id' => '2','category_id' => '2','name' => 'Working Hard','_order' => '0'),
  array('id' => '71','group_id' => '12','subcategory_id' => '2','category_id' => '2','name' => 'Leading and Managing People','_order' => '0'),
  array('id' => '72','group_id' => '12','subcategory_id' => '2','category_id' => '2','name' => 'Being Structured and Organised','_order' => '0'),
  array('id' => '73','group_id' => '12','subcategory_id' => '2','category_id' => '2','name' => 'Digesting Information','_order' => '0'),
  array('id' => '74','group_id' => '12','subcategory_id' => '2','category_id' => '2','name' => 'Taking the Initiative','_order' => '0'),
  array('id' => '75','group_id' => '12','subcategory_id' => '2','category_id' => '2','name' => 'Written Communication','_order' => '0'),
  array('id' => '76','group_id' => '12','subcategory_id' => '2','category_id' => '2','name' => 'Verbal Communication','_order' => '0'),
  array('id' => '77','group_id' => '12','subcategory_id' => '2','category_id' => '2','name' => 'Numerical Analysis','_order' => '0'),
  array('id' => '78','group_id' => '12','subcategory_id' => '2','category_id' => '2','name' => 'Quantitative Analysis','_order' => '0'),
  array('id' => '79','group_id' => '12','subcategory_id' => '2','category_id' => '2','name' => 'Juggling Responsibilit','_order' => '0'),
  array('id' => '80','group_id' => '10','subcategory_id' => '2','category_id' => '2','name' => 'Cautious','_order' => '0'),
  array('id' => '81','group_id' => '10','subcategory_id' => '2','category_id' => '2','name' => 'Aware','_order' => '0'),
  array('id' => '82','group_id' => '10','subcategory_id' => '2','category_id' => '2','name' => 'Confident','_order' => '0'),
  array('id' => '83','group_id' => '10','subcategory_id' => '2','category_id' => '2','name' => 'Entertaining','_order' => '0'),
  array('id' => '84','group_id' => '10','subcategory_id' => '2','category_id' => '2','name' => 'Decisivie','_order' => '0'),
  array('id' => '85','group_id' => '10','subcategory_id' => '2','category_id' => '2','name' => 'Charismatic','_order' => '0'),
  array('id' => '86','group_id' => '10','subcategory_id' => '2','category_id' => '2','name' => 'Creative','_order' => '0'),
  array('id' => '87','group_id' => '10','subcategory_id' => '2','category_id' => '2','name' => 'Enthusiastic','_order' => '0'),
  array('id' => '88','group_id' => '10','subcategory_id' => '2','category_id' => '2','name' => 'Helpful','_order' => '0'),
  array('id' => '89','group_id' => '10','subcategory_id' => '2','category_id' => '2','name' => 'Patient','_order' => '0'),
  array('id' => '90','group_id' => '10','subcategory_id' => '2','category_id' => '2','name' => 'Focussed','_order' => '0'),
  array('id' => '91','group_id' => '10','subcategory_id' => '2','category_id' => '2','name' => 'Determined','_order' => '0'),
  array('id' => '92','group_id' => '10','subcategory_id' => '2','category_id' => '2','name' => 'Thoughtful','_order' => '0'),
  array('id' => '93','group_id' => '10','subcategory_id' => '2','category_id' => '2','name' => 'Energetic','_order' => '0'),
  array('id' => '94','group_id' => '10','subcategory_id' => '2','category_id' => '2','name' => 'Adaptable','_order' => '0'),
  array('id' => '131','group_id' => '0','subcategory_id' => '10','category_id' => '3','name' => 'Managing Small Teams of People','_order' => '0'),
  array('id' => '132','group_id' => '0','subcategory_id' => '10','category_id' => '3','name' => 'Working to Major Deadlines','_order' => '0'),
  array('id' => '133','group_id' => '0','subcategory_id' => '10','category_id' => '3','name' => 'Liaising with the Media','_order' => '0'),
  array('id' => '134','group_id' => '0','subcategory_id' => '10','category_id' => '3','name' => 'Managing Social Media Output','_order' => '0'),
  array('id' => '135','group_id' => '0','subcategory_id' => '10','category_id' => '3','name' => 'Writing Press Releases','_order' => '0'),
  array('id' => '136','group_id' => '0','subcategory_id' => '10','category_id' => '3','name' => 'Managing Client Relationships','_order' => '0'),
  array('id' => '137','group_id' => '0','subcategory_id' => '10','category_id' => '3','name' => 'Selling Over the Phone','_order' => '0'),
  array('id' => '138','group_id' => '0','subcategory_id' => '10','category_id' => '3','name' => 'Managing Large Teams of People','_order' => '0'),
  array('id' => '139','group_id' => '0','subcategory_id' => '10','category_id' => '3','name' => 'Selling in Person','_order' => '0'),
  array('id' => '140','group_id' => '0','subcategory_id' => '10','category_id' => '3','name' => 'Strategic Decision Making','_order' => '0'),
  array('id' => '141','group_id' => '0','subcategory_id' => '10','category_id' => '3','name' => 'Organising Events','_order' => '0'),
  array('id' => '142','group_id' => '0','subcategory_id' => '10','category_id' => '3','name' => 'Presenting to Groups','_order' => '0'),
  array('id' => '143','group_id' => '0','subcategory_id' => '10','category_id' => '3','name' => 'Script/Speech Writing','_order' => '0'),
  array('id' => '144','group_id' => '0','subcategory_id' => '10','category_id' => '3','name' => 'Working with VIPs','_order' => '0'),
  array('id' => '145','group_id' => '0','subcategory_id' => '10','category_id' => '3','name' => 'Running Meetings','_order' => '0'),
  array('id' => '146','group_id' => '0','subcategory_id' => '10','category_id' => '3','name' => 'Writing Presentations','_order' => '0'),
  array('id' => '147','group_id' => '0','subcategory_id' => '10','category_id' => '3','name' => 'Writing Reports','_order' => '0'),
  array('id' => '148','group_id' => '0','subcategory_id' => '10','category_id' => '3','name' => 'Market Research and Analysis','_order' => '0')
);
